### ISSUE TITLE
KHG Menu Link broken

### ISSUE THREAD

**Issue by byte-kraken** [marunjar/anewjkuapp#133]
Due to a restructuring of the KHG's website, its URLs have changed. The menu plan (https://www.dioezese-linz.at/institution/807510/essen/menueplan) is no longer accessible in App.

**Comment by rnbdsh** [comment]
I'll work on it, as well as the choice + raab mensa parser

**Comment by rnbdsh** [comment]
Should it look like this? If yes, it's fixed and a PR exists
![Screenshot from 2019-10-21 19-14-08](https://user-images.githubusercontent.com/9084941/67227198-1093a180-f437-11e9-91f8-e5f5da1ae3b7.png)

**Comment by marunjar** [comment]
fixed with #137
