### ISSUE TITLE
Courses and Exams not syncing

### ISSUE THREAD

**Issue by narosu** [marunjar/anewjkuapp#143]
Wanted to start using the app today, but Courses and Exams are not syncing. Also the Timetable is empty and it looks like "Courses" is also showing the Grades.

Device: Xiaomi Pocophone F1
OS: LineageOS 16, Android 9
Tried the 3 versions from F-Droid and the one from the Playstore

**Comment by marunjar** [comment]
Thanks, this is the same as #141 
Should be fixed soon.
